# Generated by Django 3.2.3 on 2021-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('head0', models.CharField(default='', max_length=500)),
                ('head0_content', models.CharField(default='', max_length=50000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('head1_content', models.CharField(default='', max_length=50000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('head2_content', models.CharField(default='', max_length=50000)),
                ('publish_date', models.DateField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
