# Generated by Django 3.2.3 on 2021-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210610_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('oder_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=500000)),
                ('firist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('adress_2', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
