# Generated by Django 3.2.3 on 2021-07-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress_2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='oder_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='firist_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
    ]
